/* kiiiskTV — profile gallery and visual helpers */
(()=>{
"use strict";
const mapImages={Mirage:"../Image/Maps/mirage.jpg",Inferno:"../Image/Maps/inferno.jpg",Ancient:"../Image/Maps/ancient.jpg",Nuke:"../Image/Maps/nuke.jpg",Dust2:"../Image/Maps/dust2.jpg",Anubis:"../Image/Maps/anubis.jpg",Cache:"../Image/Maps/cache.jpg"};
document.querySelectorAll(".manual-map-card").forEach(card=>{const name=card.querySelector(".manual-map-top strong")?.textContent?.trim();if(name&&mapImages[name])card.style.setProperty("--map-bg",`url("${mapImages[name]}")`)});
const galleryHost=document.getElementById("profileGallery");if(!galleryHost)return;
const gallery=[["../Image/KDC5/KDC5_1.jpg","Kiiisk Duo Cup 5","Турнирный момент"],["../Image/KDC5/KDC5_2.jpg","Kiiisk Duo Cup 5","Матч турнира"],["../Image/KDC5/KDC5_3.jpg","Kiiisk Duo Cup 5","KiiiskTV"],["../Image/KDC5/KDC5_4.jpg","Kiiisk Duo Cup 5","Турнирная серия"],["../Image/KDC4/KDC4_1.jpg","Kiiisk Duo Cup 4","Турнирный момент"],["../Image/KDC4/KDC4_2.jpg","Kiiisk Duo Cup 4","Матч турнира"],["../Image/KDC3/KDC3_1.jpg","Kiiisk Duo Cup 3","Турнирная серия"],["../Image/KDC2/KDC2_1.jpg","Kiiisk Duo Cup 2","Турнирный момент"]];
galleryHost.innerHTML=`<div class="profile-gallery-grid">${gallery.map((item,i)=>`<button class="profile-gallery-item" type="button" data-gallery-index="${i}" aria-label="Открыть фото: ${item[1]}"><img src="${item[0]}" alt="${item[1]} — ${item[2]}" loading="lazy"><span class="profile-gallery-overlay"><strong>${item[1]}</strong><span>${item[2]}</span></span></button>`).join("")}</div><div class="profile-gallery-lightbox" id="profileGalleryLightbox" aria-hidden="true"><button class="profile-gallery-close" type="button" aria-label="Закрыть">×</button><img src="" alt=""><div class="profile-gallery-caption"></div></div>`;
const lightbox=galleryHost.querySelector("#profileGalleryLightbox"),img=lightbox.querySelector("img"),caption=lightbox.querySelector(".profile-gallery-caption");const close=()=>{lightbox.classList.remove("is-open");lightbox.setAttribute("aria-hidden","true");document.body.style.overflow=""};galleryHost.querySelectorAll(".profile-gallery-item").forEach(btn=>btn.addEventListener("click",()=>{const item=gallery[Number(btn.dataset.galleryIndex)];if(!item)return;img.src=item[0];img.alt=`${item[1]} — ${item[2]}`;caption.textContent=`${item[1]} · ${item[2]}`;lightbox.classList.add("is-open");lightbox.setAttribute("aria-hidden","false");document.body.style.overflow="hidden"}));lightbox.querySelector(".profile-gallery-close").addEventListener("click",close);lightbox.addEventListener("click",e=>{if(e.target===lightbox)close()});document.addEventListener("keydown",e=>{if(e.key==="Escape")close()});
})();
